load("//mediapipe/java/com/google/mediapipe:mediapipe_aar.bzl", "mediapipe_aar")

mediapipe_aar(
    name = "mp_objectdetection3d_aar",
    calculators = ["//mediapipe/graphs/object_detection_3d:mobile_calculators"],
)
